name: bitfinex-framework
description: "Bitfinex Mobile Automation Framework with MCP Integration"

# Framework configuration
framework:
  defaultPlatform: "android"
  defaultMode: "lite"
  defaultPinIterations: 9
  defaultTestFile: "tests"
  defaultEnvironment: "staging"
  defaultTestScope: "smoke"

# App mode configuration
modes:
  lite:
    name: "Lite"
    description: "Lite mode with basic features"
    selector: "Lite.*"
    timeout: 10000
    features: ["basic_trading", "wallet_view", "simple_navigation"]
  full:
    name: "Full"
    description: "Full mode with all features"
    selector: "Full.*"
    timeout: 15000
    features: ["advanced_trading", "full_wallet", "complete_navigation", "analytics", "advanced_orders"]

# App configurations
apps:
  android:
    appId: "com.bitfinex.bfxdev"
    name: "Bitfinex Android"
    packageName: "com.bitfinex.bfxdev"
    apkPath: "apps/bitfinex-android.apk"
  ios:
    appId: "com.bitfinex.bfxdev"
    name: "Bitfinex iOS"
    bundleId: "com.bitfinex.bfxdev"
    appPath: "apps/BitfinexRedesign.app"

# Test data configuration
testdata:
  staging: "testdata/testdata-staging.js"
  prod: "testdata/testdata-prod.js"
  
# Test scope configuration
testScopes:
  smoke:
    tags: ["smoke", "login", "critical"]
    description: "Quick smoke tests for basic functionality"
    timeout: 300
  full:
    tags: ["smoke", "login", "navigation", "end-to-end", "regression", "critical", "ui"]
    description: "Complete test suite including all test types"
    timeout: 1800

# Flow directories
flows:
  shared: "flows/shared"
  tests: "tests"
  utils: "utils"

# Reports configuration
reports:
  output: "reports"
  screenshots: "reports/screenshots"
  recordings: "reports/recordings"
  debug: "debug"

# MCP configuration
mcp:
  enabled: true
  server: "maestro"
  timeout: 30000
  verbose: true
  
# Environment configuration
environments:
  staging:
    name: "Staging Environment"
    testdata: "testdata/testdata-staging.js"
    timeout: 15000
  prod:
    name: "Production Environment"
    testdata: "testdata/testdata-prod.js"
    timeout: 20000
